### ISSUE TITLE
Final room for night

### ISSUE THREAD

**Issue by tommytran0** [FibreKitty/FuzzyLogic-Web#14]
Scenario we're in right now:
For Saturday, August 26, in Casino, we currently have it set for a 60 minute run time with 60 min reset time for testing purposes. I noticed it omits the 10PM time slot. Is the code considering reset time as a part of the room? Because resetting can occur after closing. It does not affect the customer experience since all would have left by then. 

![image](https://user-images.githubusercontent.com/30819580/29496637-47d571e8-859c-11e7-85e5-eacf75a239f3.png)

**Comment by FibreKitty** [comment]
It considers reset time as part of the total time.

Are you asking for it to not consider the reset time with respect to running past the closing time?

**Comment by tommytran0** [comment]
Yes, correct. since there no potential conflicts after closing

**Comment by FibreKitty** [comment]
Done; room reset times are not considered when looking for closing time overlap.

**Comment by tommytran0** [comment]
Currently, Casino is set for 60 run time, 20 minute reset time with a 10 minute offset (starts at 4:10pm) on Saturday, Sept 2nd. There is a slot at 1130pm somehow. That can't be there since the room is 60 min and it would run until 1230am

**Comment by FibreKitty** [comment]
Math error; fixed

**Comment by tommytran0** [comment]
Vet office is set with 60 minute run times and 0 minute reset times currently. For a thursday, there is a 4pm,5pm, a 6 pm, a 7pm and a 8pm but no 9pm room slot

**Comment by FibreKitty** [comment]
Done; exclusive comparison logic fixed, now properly includes slots that will go right up to the cut off time.
