### ISSUE TITLE
Booking slot names

### ISSUE THREAD

**Issue by tommytran0** [FibreKitty/FuzzyLogic-Web#15]
Currently room slots show up as simply the day and time of slot. Example: "2017-08-20 @19:00"

Can we omit the year from the default title and also include:
- room
- name of booker
- party size

This would save us having to manually enter this info every booking

**Comment by FibreKitty** [comment]
Please clarify what you mean by "slots show up as". Time slots show up different depending on context.

**Comment by tommytran0** [comment]
![image](https://user-images.githubusercontent.com/30819580/29496776-2747e412-859f-11e7-8e28-2dc6a9e018ed.png)

The highlighted is default. This is where we would like the above info to be displayed by default upon room booking

**Comment by FibreKitty** [comment]
This can't work. All titles have to be unique. The same booker could book the same room with the wanna party size on two different days, and it would fail. A unique identifier (such as the date) has to be in it somewhere

**Comment by tommytran0** [comment]
Can you include just the month and date, then?

And does this mean that a person wouldn't be able to, for example, book a room for two slots, then come back to the same timeslot and room and book for two more slots?

**Comment by FibreKitty** [comment]
> And does this mean that a person wouldn't be able to, for example, book a room for two slots, then come back to the same timeslot and room and book for two more slots?
Correct, but I can set it to separate title and URL creation to allow for non-distinct titles.

> Can you include just the month and date, then?
How about this for a title: "[room], [name], [partysize] - ([datetime]).
I still recommend ISO 8601 date formats( yyyy-mm-dd ) since it's an industry standard, and removes ambiguity, especially in the long term.

**Comment by tommytran0** [comment]
That title format is acceptable. And if that scenario i described works, then good because I have personally been in that situation to add additional members to a current booking.

**Comment by FibreKitty** [comment]
Done; title format updated, and multiple distinct titles can be added (multiple identical bookings)

**Comment by tommytran0** [comment]
Fantastic. Thank you
