### ISSUE TITLE
book a room party size on scrolling

### ISSUE THREAD

**Issue by tommytran0** [FibreKitty/FuzzyLogic-Web#16]
After filling in personal info and choosing a room and party size, scrolling through dates resets the party size to 1.

**Comment by FibreKitty** [comment]
Each room can have different sizes, and therefore different allowed party sizes. The size list refreshes for each room. To avoid confusion.

**Comment by tommytran0** [comment]
I'm leaving the party size and room choice the same and just browsing through different dates.

**Comment by FibreKitty** [comment]
Would you like the party size to remain consistent while scrolling through dates?

**Comment by FibreKitty** [comment]
I will assume yes. Done.

**Comment by tommytran0** [comment]
Yes to party size consistency.  Clearing browser cache and reattempting.

**Comment by tommytran0** [comment]
Successful, thank you
