### ISSUE TITLE
Booking a room shows up one hour off

### ISSUE THREAD

**Issue by tommytran0** [FibreKitty/FuzzyLogic-Web#17]
Tried to book a room for today at 3:20 in Time Pirates.

Upon confirmation screen, the time slot is now displayed as 4:20. And since there is not a 4:20 time slot, all the slots of the day still show up as empty.

**Comment by FibreKitty** [comment]
See if it still is present

**Comment by tommytran0** [comment]
First test passed. confirmation screen accurate. admin panel shows accurate time and slots are reduced on future bookings
