### ISSUE TITLE
Room max capacity

### ISSUE THREAD

**Issue by tommytran0** [FibreKitty/FuzzyLogic-Web#18]
Changing a room max capacity doesn't notify us when there are already bookings in place with that room in the future. 

Also max capacity is able to be set to be 0.

**Comment by FibreKitty** [comment]
Max capacity must now be at least 1.

Creating actions when a page field changes in admin mode will require the implementation of additional functionality. Not sure how long this will take. Is this important? Will room capacity change frequently?

**Comment by tommytran0** [comment]
This becomes less of a concern if #15 were addressed. We could just Ctrl F for bookings in a given room.

**Comment by FibreKitty** [comment]
Then please address #15

**Comment by FibreKitty** [comment]
Is this still an issue?

**Comment by tommytran0** [comment]
No, this can be closed. Thank you
