### ISSUE TITLE
Overbooking a room

### ISSUE THREAD

**Issue by tommytran0** [FibreKitty/FuzzyLogic-Web#20]
I was somehow able to overbook Vet office Sept 9 for over its capacity by using two browser windows. The available spaces now lists as "-2"

Will attempt to replicate

**Comment by tommytran0** [comment]
replicated with Vet office Aug 31 at 5:15pm

**Comment by FibreKitty** [comment]
Unable to replicate; normal prevention measures kick in.

Please detail exact steps. (you should always do this)

**Comment by tommytran0** [comment]
1. fill out personal info in two browser windows, one Firefox, one Chrome. 
2. Choose vet office, "Drew" (in Chrome) will have party size 6, "Tommy" (Firefox) will have party size 3
3. Both choose 4PM, Aug 29th
4. Drew hits "Continue, then Tommy hits "Continue"
5. Both successfully reach confirmation screen
6. Drew hits "Continue to payment", then Tommy does as well. 
7. Drew puts in his payment info first and sends payment via square, then Tommy does as well. 
8. Drew gets to "Booking Successful" screen, then Tommy does as well. 

![image](https://user-images.githubusercontent.com/30819580/29497980-537c2520-85b8-11e7-9dca-10b25be99074.png)

**Comment by FibreKitty** [comment]
Ran through these exact steps, got kicked back to the front with "ERROR: Your booking is invalid" during the second part of step 4, as expected.

Can others confirm this?

**Comment by tommytran0** [comment]
Arc is trying it now on his machine

**Comment by FibreKitty** [comment]
I think I found the issue. Believe it's fixed, let me know

**Comment by tommytran0** [comment]
"Your booking is invalid" upon step 4. replicated with Arc.

**Comment by FibreKitty** [comment]
Good, this is expected

**Comment by FibreKitty** [comment]
Is this issue still present?

**Comment by tommytran0** [comment]
We are not able to replicate the error again. We can close it
