### ISSUE TITLE
Book a room party size

### ISSUE THREAD

**Issue by tommytran0** [FibreKitty/FuzzyLogic-Web#21]
Upon clicking on and arriving at Book a room, the party size for Casino is "1". If I select a different room then come back to Casino, it shows the correct 1-8 options

Same for if I'm on the "Escape Rooms" description and I click on "Time Pirates" It'll select time pirates for me and show a party size of "1" with no higher options until I select a different room.

**Comment by FibreKitty** [comment]
Done; party sizes properly filled in on page load
