### ISSUE TITLE
Book a room size doesn't disallow overbooking a room

### ISSUE THREAD

**Issue by FibreKitty** [FibreKitty/FuzzyLogic-Web#5]
[imported from GitLab]

If Party A books out a room for 5 people for a given slot. Party B of 4 people can then come in later and successfully make a booking in the exact same timeslot
Solution: Limit party size selection to be remaining spots in the room?

**Comment by FibreKitty** [comment]
@tommytran0 
Unable to replicate this issue. Rooms that are booked out show up as FULL, and once a certain party size is selected, rooms that don't have enough space will automatically change to FULL.

Please confirm that you still experience this issue and document the exact steps taken.

**Comment by tommytran0** [comment]
I'm also unable to replicate. Will test again when completed.
