### ISSUE TITLE
Hours of operation

### ISSUE THREAD

**Issue by tommytran0** [FibreKitty/FuzzyLogic-Web#7]
![image](https://user-images.githubusercontent.com/30819580/29464340-3501cee2-83fb-11e7-8e6f-7e30776f5b8b.png)

Putting hours of 8am to midnight seems to break the room for the day

I also noticed a typo in the "HH:MM-HH-MM"

**Comment by FibreKitty** [comment]
@tommytran0 
Please specify "midnight". It only accepts numerical values.

**Comment by tommytran0** [comment]
Ah, so I should use 24:00?

**Comment by FibreKitty** [comment]
@tommytran0 
You need to be more specific with bug descriptions. You could not have entered "midnight", because it accepts numerical values only. What did you enter?

**Comment by tommytran0** [comment]
i had put in 00:00

**Comment by FibreKitty** [comment]
Fixed, specifying 00:00 as midnight behaves as expected
